http {

    upstream api_cluster {
        server api:4000;
        server api:4000;
        server api:4000;
    }

    # http setup
    server {
        listen       80;
        server_name localhost;

        # redirect to https
        location / {
            return 301 https://$host$request_uri;
        }
    }

    # https configuration
    server {
        listen 443 ssl;
        server_name localhost;

        ssl_certificate /etc/nginx/ssl/nginx-selfsigned.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx-selfsigned.key;

        location / {
            proxy_pass http://api_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}

events {
}